name: Auto Pull Request
on:
  push:
    branches:
      - PROD*
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: "auto-pr ${{ env.BRANCH_NAME }}"
        base: ${{ env.BRANCH_NAME }}
        commit-message: Auto Pull Request
        title: Auto Pull Request
        body: Auto Pull Request
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
