name: Auto Pull Request
on:
  push:
    branches:
    - BC*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: PROD_DE
        github_token: ${{ secrets.GITHUB_TOKEN }}